import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import { motion } from "framer-motion";

export default function Disclaimer() {
  return (
    <div className="min-h-screen p-6">
      <div className="max-w-2xl mx-auto space-y-10">
        <div className="flex items-center justify-between">
          <Link href="/">
            <button className="flex items-center gap-2 text-sm uppercase tracking-widest text-muted-foreground hover:text-foreground transition-colors" data-testid="link-back">
              <ArrowLeft className="h-4 w-4" />
              Back
            </button>
          </Link>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-10"
        >
          <div>
            <h1 className="text-4xl font-bold uppercase tracking-tighter">Terms of Use</h1>
            <p className="text-sm text-muted-foreground mt-2">
              Please read the following carefully before using Reckon.
            </p>
          </div>

          <div className="space-y-8">
            <section className="space-y-3">
              <h2 className="text-lg font-bold uppercase tracking-wider">1. Purpose and Scope</h2>
              <div className="border-l-4 border-[#5B7B6A] pl-4 space-y-2">
                <p className="text-sm leading-relaxed text-muted-foreground">
                  Reckon is a cognitive exercise tool designed to assist users in structuring their thinking around decisions, beliefs, and trade-offs. The tools provided — including the counterargument scorer, Weigh It Up, and Unthread — are intended solely as guides to support personal reflection and decision-making processes.
                </p>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  This platform does not provide professional advice of any kind, including but not limited to financial, legal, medical, or psychological advice. It should not be used as a substitute for qualified professional consultation.
                </p>
              </div>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold uppercase tracking-wider">2. Use of Artificial Intelligence</h2>
              <div className="border-l-4 border-[#5B7B6A] pl-4 space-y-2">
                <p className="text-sm leading-relaxed text-muted-foreground">
                  This website uses artificial intelligence to process and analyse the information you provide. While the AI operates locally within the application where possible, users should be mindful of the information they enter.
                </p>
                <p className="text-sm leading-relaxed text-muted-foreground font-medium text-foreground">
                  We strongly advise against entering personally identifiable information, sensitive data, or confidential details into any of the tools on this platform. This includes but is not limited to full names, addresses, financial details, health information, or any data that could be used to identify you or others.
                </p>
              </div>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold uppercase tracking-wider">3. Limitation of Liability</h2>
              <div className="border-l-4 border-[#5B7B6A] pl-4 space-y-2">
                <p className="text-sm leading-relaxed text-muted-foreground">
                  Reckon and its creators accept no responsibility or liability for any decisions made, actions taken, or outcomes arising from the use of this tool. The results, scores, and insights generated by this platform are intended to provoke thought and facilitate structured reasoning — they are not directives, recommendations, or endorsements of any particular course of action.
                </p>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  Users acknowledge that they bear full responsibility for any decisions they make, whether or not those decisions are informed by the use of this platform.
                </p>
              </div>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold uppercase tracking-wider">4. Data Handling</h2>
              <div className="border-l-4 border-[#5B7B6A] pl-4 space-y-2">
                <p className="text-sm leading-relaxed text-muted-foreground">
                  Information entered into Reckon is processed in real time and is not stored, saved, or retained beyond the duration of your active session. Once you leave or refresh the page, all data you have entered is permanently discarded.
                </p>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  Notwithstanding the above, users should exercise caution and avoid entering information they would not be comfortable sharing in a non-secure environment.
                </p>
              </div>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold uppercase tracking-wider">5. Acceptance</h2>
              <div className="border-l-4 border-[#5B7B6A] pl-4 space-y-2">
                <p className="text-sm leading-relaxed text-muted-foreground">
                  By using Reckon, you acknowledge that you have read, understood, and agree to these terms. Continued use of the platform constitutes acceptance of these conditions in full.
                </p>
              </div>
            </section>
          </div>

          <div className="border-t-2 border-muted pt-6 pb-12">
            <Link href="/">
              <button className="text-sm uppercase tracking-widest text-muted-foreground hover:text-foreground transition-colors" data-testid="link-back-bottom">
                <ArrowLeft className="h-4 w-4 inline mr-2" />
                Return to Reckon
              </button>
            </Link>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
